feat: ca specs update and registered user response added
fabric8-analytics/fabric8-analytics-server pull request #668
Opened 2020-08-24 09:58 UTC by deepak1725

CA Specs in Sync with CA Response Updated.
Registered User Response Handled.

Jira: https://issues.redhat.com/browse/APPAI-1449 

Signed-off-by: Deepak Sharma <deepshar@redhat.com>

2020-08-24 16:21 UTC, prashbnair requested changes

2020-08-24 16:21 UTC, prashbnair commented on api_specs/v2/component_analyses.yaml
> -          recommendation:
this field is still there in the spec definition

2020-08-24 16:21 UTC, prashbnair commented on bayesian/utility/v2/ca_response_builder.py
> +            version=self.version,
The names of the fields in the premium response are different from the normal response, will this work in the UI?

2020-08-25 06:20 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
> +            - id: "SNYK-2010-3082"
Overall there is 3 Major Difference in response:
|                                   | Free User         | Registered User |
|-----------------------------------|-------------------|-----------------|
| exploitable_vulnerabilities_count | No                | Yes             |
| premium_message                   | No                | Yes             |
| link                              | registration_link | package_link    |

Please see Specs here
https://app.swaggerhub.com/apis/deepak1725/analytics-core_api_specs_for_version_2/2.1#/CA%20batch%20call/post_component_analyses_

2020-08-25 06:27 UTC, deepak1725 commented on bayesian/utility/v2/ca_response_builder.py
> +            version=self.version,
@prashbnair There is only 1 field name change

In Free Response, there is `registration_link` whereas in Premium Response we will get `vendor_package_link`
and
1 field is added in Premium Response, which was not a part of FreeTier Response: `exploitable_vulnerabilities_count`

That's what we settled with, in https://app.swaggerhub.com/apis/deepak1725/analytics-core_api_specs_for_version_2/2.1#/CA%20batch%20call/post_component_analyses

2020-08-25 09:04 UTC, prashbnair requested changes

2020-08-25 09:04 UTC, prashbnair commented on bayesian/utility/v2/ca_response_builder.py
> +            version=self.version,
Why do you have the package, version fields?
The component_analyses field is missing, severity is named highest_severity.

2020-08-25 10:02 UTC, deepak1725 commented on bayesian/utility/v2/ca_response_builder.py
> +            version=self.version,
> Why do you have the package, version fields?
@prashbnair This is Requested change by you to include version, package in each Package Recommendation.
I think we had a discussion regarding this in https://github.com/fabric8-analytics/fabric8-analytics-server/pull/655

>  The component_analyses field is missing, severity is named highest_severity.
Again this discussion happened in the mentioned PR. Please note I'm not unilaterally changing anything.

2020-08-25 10:03 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
> +            - id: "SNYK-2010-3082"
No, there is no difference in the Vulnerability level.

2020-08-25 10:16 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
> +          vulnerabilities:
In PR #655, There was a proposal to move schema towards more cleaner level. The proposal was to change 
`componenet_analyses->vulnerabilities->cve_info[array]`  nesting to `vulnerabilities->cve_info[array]` only.

I'm Not introducing any new changes, but all these changes are already discussed and agreed.

2020-08-25 10:16 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
> +          registeration_link: "https://app.snyk.io/login"
ack!

2020-08-25 10:19 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
>        value:
As `exploitable_vul_count` is missing, the example is of FreeTier Response Please note with few fields modified, same can be replicated for Registered User

2020-08-25 10:50 UTC, deepak1725 commented on api_specs/v2/component_analyses.yaml
> +          vulnerabilities:
ack! Removed Recommendation nesting from Every Schema

2020-08-25 12:18 UTC, prashbnair approved these changes

2020-08-25 13:44 UTC, merged